name: PR Title Validation

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Title Format
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            chore
            revert
          requireScope: true
          scopes: |
            olx-\d+
          subjectPattern: ^.+$
          subjectPatternError: |
            The subject must not be empty.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
